language: generic
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_2a68b6131c57_key -iv $encrypted_2a68b6131c57_iv
  -in root_key.enc -out root_key -d
- git submodule update --init --recursive
install:
- source ci/travis/travis_install.sh
env:
  global:
  - YCM_CORES=3
  - COVERAGE=true
  matrix:
  - YCM_PYTHON_VERSION=2.7
  - YCM_PYTHON_VERSION=3.5
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
    packages:
    - cmake-data
    - cmake
    - g++-4.8
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
before_script:
- bash test_mypy.sh
